In [ ]:
documents=["Albert Einstein was a theoretical physicist who developed the theory of relativity.",
    "Isaac Newton formulated the laws of motion and universal gravitation.",
    "Marie Curie conducted pioneering research on radioactivity and won two Nobel Prizes.",
    "Nikola Tesla was known for his contributions to the design of the modern AC electricity supply system.",
    "Stephen Hawking was a theoretical physicist who worked on black holes and cosmology."
    ]


In [1]:
!pip install sentence-transformers

In [2]:
from sentence_transformers import SentenceTransformer

In [ ]:
#loading pretrained sentence transformer model
model_name="sentence-transformers/paraphrase-xlm-r-multilingual-v1"

In [ ]:
model=SentenceTransformer(model_name)

/usr/local/lib/python3.11/dist-packages/huggingface_hub/utils/_auth.py:104: UserWarning: 
Error while fetching `HF_TOKEN` secret value from your vault: 'Requesting secret HF_TOKEN timed out. Secrets can only be fetched when running from the Colab UI.'.
You are not authenticated with the Hugging Face Hub in this notebook.
If the error persists, please let us know by opening an issue on GitHub (https://github.com/huggingface/huggingface_hub/issues/new).
  warnings.warn(


modules.json:   0%|          | 0.00/229 [00:00<?, ?B/s]

config_sentence_transformers.json:   0%|          | 0.00/122 [00:00<?, ?B/s]

README.md: 0.00B [00:00, ?B/s]

sentence_bert_config.json:   0%|          | 0.00/53.0 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/718 [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/1.11G [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/550 [00:00<?, ?B/s]

sentencepiece.bpe.model:   0%|          | 0.00/5.07M [00:00<?, ?B/s]

tokenizer.json: 0.00B [00:00, ?B/s]

special_tokens_map.json:   0%|          | 0.00/150 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/190 [00:00<?, ?B/s]

In [ ]:
documents

['Albert Einstein was a theoretical physicist who developed the theory of relativity.',
 'Isaac Newton formulated the laws of motion and universal gravitation.',
 'Marie Curie conducted pioneering research on radioactivity and won two Nobel Prizes.',
 'Nikola Tesla was known for his contributions to the design of the modern AC electricity supply system.',
 'Stephen Hawking was a theoretical physicist who worked on black holes and cosmology.']

In [ ]:
len(documents)

5

In [ ]:
document_embeddings=model.encode(documents)

In [ ]:
len(document_embeddings)

5

In [ ]:
len(document_embeddings[0])

768

In [ ]:
for i, embedding in enumerate(document_embeddings):
  print(f"Document {i+1} Embedding: {embedding}")

Document 1 Embedding: [ 3.94026116e-02  3.59080404e-01  9.52500030e-02  3.18636388e-01
 -1.11138955e-01  4.52717274e-01  3.07657123e-02  5.22289947e-02
  2.19355583e-01 -2.82222748e-01 -2.61587292e-01 -3.19600642e-01
  5.09502105e-02 -1.04122363e-01 -2.75918603e-01 -3.42973113e-01
  9.49908942e-02  1.70190096e-01 -4.37610000e-02 -4.88394141e-01
  2.18780898e-02 -3.97821188e-01 -1.17725031e-02  1.00937344e-01
  3.97802979e-01  1.76801503e-01  4.66578901e-01  2.04356745e-01
  8.28623027e-02  3.76118481e-01 -1.26417086e-01 -1.70363247e-01
 -8.95821527e-02  1.86722856e-02  3.36680934e-02 -1.64010406e-01
 -2.22720265e-01  3.23373713e-02  1.50237292e-01  1.62753478e-01
  3.59231055e-01  1.74528241e-01 -1.19695529e-01  1.24707311e-01
 -1.64367422e-01 -5.58946967e-01 -3.83931488e-01 -9.75331441e-02
  3.46175916e-02  8.25518072e-02  2.12985873e-01  6.76848739e-02
  2.23531500e-01 -1.67573899e-01 -2.09989935e-01 -7.86523595e-02
  4.61546406e-02  2.47883573e-01  2.01523751e-01  2.23793194e-01
 -6

In [ ]:
query="Who developed the theory of relativity?"

In [ ]:
quer_embedding=model.encode(query)

In [ ]:
quer_embedding

array([ 1.44280195e-01,  8.24094787e-02,  1.76502213e-01,  3.19494247e-01,
       -1.65329855e-02,  5.18811405e-01,  1.26350850e-01,  1.85811177e-01,
        2.03174591e-01, -2.78022081e-01, -1.40063465e-01, -2.47285720e-02,
       -4.69571799e-02, -2.34565407e-01, -2.92374752e-02, -1.87278509e-01,
       -1.86083212e-01,  1.18884340e-01,  6.97091818e-02, -3.09787422e-01,
       -8.56520832e-02, -2.81233013e-01, -1.88149288e-01,  2.91726887e-01,
        2.68537048e-02,  1.51361167e-01,  1.78591162e-01,  6.96839690e-02,
        1.30542427e-01,  2.89200008e-01,  1.59385383e-01, -6.61455616e-02,
        3.28511372e-03, -8.20188969e-02, -2.21023709e-01, -1.38100758e-01,
       -1.29215389e-01, -4.19974811e-02, -5.70828840e-02,  2.24858686e-01,
        1.71742186e-01,  6.75485581e-02, -1.15260936e-01,  1.43677846e-01,
       -2.46794850e-01, -3.67160827e-01, -2.01341227e-01,  6.05763420e-02,
       -7.88235888e-02,  6.51477128e-02,  2.02462390e-01, -1.21783771e-01,
        3.29658210e-01, -

In [ ]:
len(quer_embedding)

768

In [ ]:
import numpy as np
from sklearn.metrics.pairwise import cosine_similarity

In [ ]:
similarities=cosine_similarity(np.array([quer_embedding]),document_embeddings)

In [ ]:
similarities

array([[0.72589016, 0.37090066, 0.3443206 , 0.18402697, 0.3504373 ]],
      dtype=float32)

In [ ]:
most_similar_index=np.argmax(similarities)

In [ ]:
most_similar_index

np.int64(0)

In [ ]:
most_similar_document=documents[most_similar_index]

In [ ]:
most_similar_document

'Albert Einstein was a theoretical physicist who developed the theory of relativity.'

In [ ]:
query

'Who developed the theory of relativity?'

In [ ]:
similarity_score=similarities[0][most_similar_index]

In [ ]:
similarity_score

np.float32(0.72589016)

In [ ]:
sorted_indices=np.argsort(similarities[0])[::-1]

In [ ]:
sorted_indices

array([0, 1, 4, 2, 3])

In [ ]:
ranked_documents=[(documents[i],similarities[0][i]) for i in sorted_indices]

In [ ]:
ranked_documents

[('Albert Einstein was a theoretical physicist who developed the theory of relativity.',
  np.float32(0.72589016)),
 ('Isaac Newton formulated the laws of motion and universal gravitation.',
  np.float32(0.37090066)),
 ('Stephen Hawking was a theoretical physicist who worked on black holes and cosmology.',
  np.float32(0.3504373)),
 ('Marie Curie conducted pioneering research on radioactivity and won two Nobel Prizes.',
  np.float32(0.3443206)),
 ('Nikola Tesla was known for his contributions to the design of the modern AC electricity supply system.',
  np.float32(0.18402697))]

In [ ]:
print("Ranked Documents:")
for rank, (document, similarity) in enumerate(ranked_documents, start=1):
    print(f"Rank {rank}: Document - '{document}', Similarity Score - {similarity}")

Ranked Documents:
Rank 1: Document - 'Albert Einstein was a theoretical physicist who developed the theory of relativity.', Similarity Score - 0.7258901596069336
Rank 2: Document - 'Isaac Newton formulated the laws of motion and universal gravitation.', Similarity Score - 0.3709006607532501
Rank 3: Document - 'Stephen Hawking was a theoretical physicist who worked on black holes and cosmology.', Similarity Score - 0.35043731331825256
Rank 4: Document - 'Marie Curie conducted pioneering research on radioactivity and won two Nobel Prizes.', Similarity Score - 0.3443205952644348
Rank 5: Document - 'Nikola Tesla was known for his contributions to the design of the modern AC electricity supply system.', Similarity Score - 0.18402697145938873


In [ ]:
print("Top 4 Documents:")
for rank, (document, similarity) in enumerate(ranked_documents[:4], start=1):
    print(f"Rank {rank}: Document - '{document}', Similarity Score - {similarity}")

Top 4 Documents:
Rank 1: Document - 'Albert Einstein was a theoretical physicist who developed the theory of relativity.', Similarity Score - 0.7258901596069336
Rank 2: Document - 'Isaac Newton formulated the laws of motion and universal gravitation.', Similarity Score - 0.3709006607532501
Rank 3: Document - 'Stephen Hawking was a theoretical physicist who worked on black holes and cosmology.', Similarity Score - 0.35043731331825256
Rank 4: Document - 'Marie Curie conducted pioneering research on radioactivity and won two Nobel Prizes.', Similarity Score - 0.3443205952644348


In [ ]:
!pip install rank_bm25

In [ ]:
from rank_bm25 import BM25Okapi

In [ ]:
top_4_documents=[doc[0] for doc in ranked_documents[:4]]

In [ ]:
top_4_documents

['Albert Einstein was a theoretical physicist who developed the theory of relativity.',
 'Isaac Newton formulated the laws of motion and universal gravitation.',
 'Stephen Hawking was a theoretical physicist who worked on black holes and cosmology.',
 'Marie Curie conducted pioneering research on radioactivity and won two Nobel Prizes.']

In [ ]:
tokenized_top_4_document=[doc.split() for doc in top_4_documents]

In [ ]:
tokenized_top_4_document

[['Albert',
  'Einstein',
  'was',
  'a',
  'theoretical',
  'physicist',
  'who',
  'developed',
  'the',
  'theory',
  'of',
  'relativity.'],
 ['Isaac',
  'Newton',
  'formulated',
  'the',
  'laws',
  'of',
  'motion',
  'and',
  'universal',
  'gravitation.'],
 ['Stephen',
  'Hawking',
  'was',
  'a',
  'theoretical',
  'physicist',
  'who',
  'worked',
  'on',
  'black',
  'holes',
  'and',
  'cosmology.'],
 ['Marie',
  'Curie',
  'conducted',
  'pioneering',
  'research',
  'on',
  'radioactivity',
  'and',
  'won',
  'two',
  'Nobel',
  'Prizes.']]

In [ ]:
tokenized_query=query.split()

In [ ]:
tokenized_query

['Who', 'developed', 'the', 'theory', 'of', 'relativity?']

In [ ]:
bm25=BM25Okapi(tokenized_top_4_document)

In [ ]:
bm25

In [ ]:
bm25_scores=bm25.get_scores(tokenized_query)

In [ ]:
bm25_scores

array([1.67852474, 0.        , 0.        , 0.        ])

In [ ]:
sorted_indices2=np.argsort(bm25_scores)[::-1]

In [ ]:
sorted_indices2

array([0, 3, 2, 1])

In [ ]:
top_4_documents

['Albert Einstein was a theoretical physicist who developed the theory of relativity.',
 'Isaac Newton formulated the laws of motion and universal gravitation.',
 'Stephen Hawking was a theoretical physicist who worked on black holes and cosmology.',
 'Marie Curie conducted pioneering research on radioactivity and won two Nobel Prizes.']

In [ ]:
reranked_documents=[(top_4_documents[i],bm25_scores[i]) for i in sorted_indices2]

In [ ]:
reranked_documents

[('Albert Einstein was a theoretical physicist who developed the theory of relativity.',
  np.float64(1.6785247392286016)),
 ('Marie Curie conducted pioneering research on radioactivity and won two Nobel Prizes.',
  np.float64(0.0)),
 ('Stephen Hawking was a theoretical physicist who worked on black holes and cosmology.',
  np.float64(0.0)),
 ('Isaac Newton formulated the laws of motion and universal gravitation.',
  np.float64(0.0))]

CROSS-Encoder

In [ ]:
from sentence_transformers import CrossEncoder

In [ ]:
cross_encoder=CrossEncoder("cross-encoder/ms-marco-MiniLM-L-6-v2")

config.json:   0%|          | 0.00/794 [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/90.9M [00:00<?, ?B/s]

tokenizer_config.json: 0.00B [00:00, ?B/s]

vocab.txt: 0.00B [00:00, ?B/s]

tokenizer.json: 0.00B [00:00, ?B/s]

special_tokens_map.json:   0%|          | 0.00/132 [00:00<?, ?B/s]

README.md: 0.00B [00:00, ?B/s]

In [ ]:
top_4_documents

['Albert Einstein was a theoretical physicist who developed the theory of relativity.',
 'Isaac Newton formulated the laws of motion and universal gravitation.',
 'Stephen Hawking was a theoretical physicist who worked on black holes and cosmology.',
 'Marie Curie conducted pioneering research on radioactivity and won two Nobel Prizes.']

In [ ]:
pairs=[]
for doc in top_4_documents:
  pairs.append([query,doc])

In [ ]:
pairs

[['Who developed the theory of relativity?',
  'Albert Einstein was a theoretical physicist who developed the theory of relativity.'],
 ['Who developed the theory of relativity?',
  'Isaac Newton formulated the laws of motion and universal gravitation.'],
 ['Who developed the theory of relativity?',
  'Stephen Hawking was a theoretical physicist who worked on black holes and cosmology.'],
 ['Who developed the theory of relativity?',
  'Marie Curie conducted pioneering research on radioactivity and won two Nobel Prizes.']]

In [ ]:
scores=cross_encoder.predict(pairs)
scores

array([10.762376 ,  2.2295616, -5.0766177, -6.810939 ], dtype=float32)

In [ ]:
scored_docs=zip(scores,top_4_documents)

In [ ]:
scored_docs

In [ ]:
reranked_document_cross_encoder=sorted(scored_docs,reverse=True)

In [ ]:
reranked_document_cross_encoder

[(np.float32(10.762376),
  'Albert Einstein was a theoretical physicist who developed the theory of relativity.'),
 (np.float32(2.2295616),
  'Isaac Newton formulated the laws of motion and universal gravitation.'),
 (np.float32(-5.0766177),
  'Stephen Hawking was a theoretical physicist who worked on black holes and cosmology.'),
 (np.float32(-6.810939),
  'Marie Curie conducted pioneering research on radioactivity and won two Nobel Prizes.')]

BM_25 rerank docs

In [ ]:
reranked_documents

[('Albert Einstein was a theoretical physicist who developed the theory of relativity.',
  np.float64(1.6785247392286016)),
 ('Marie Curie conducted pioneering research on radioactivity and won two Nobel Prizes.',
  np.float64(0.0)),
 ('Stephen Hawking was a theoretical physicist who worked on black holes and cosmology.',
  np.float64(0.0)),
 ('Isaac Newton formulated the laws of motion and universal gravitation.',
  np.float64(0.0))]

Cohere

In [ ]:
!pip install cohere

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 291.9/291.9 kB 7.9 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.3/3.3 MB 68.2 MB/s eta 0:00:00


In [ ]:
import cohere

In [ ]:
co=cohere.Client("LjAFlAQeghbxtPD1hFN2cJ2Fs2fjXaNiTUHHi445")

In [ ]:
response=co.rerank(
    model="rerank-english-v3.0",
    query=query,
    documents=top_4_documents,
    return_documents=True
)

In [ ]:
print(response)

id='6046e276-6528-4108-af5f-a4b1c8a9ea36' results=[RerankResponseResultsItem(document=RerankResponseResultsItemDocument(text='Albert Einstein was a theoretical physicist who developed the theory of relativity.'), index=0, relevance_score=0.99931216), RerankResponseResultsItem(document=RerankResponseResultsItemDocument(text='Isaac Newton formulated the laws of motion and universal gravitation.'), index=1, relevance_score=0.050705366), RerankResponseResultsItem(document=RerankResponseResultsItemDocument(text='Marie Curie conducted pioneering research on radioactivity and won two Nobel Prizes.'), index=3, relevance_score=0.028167473), RerankResponseResultsItem(document=RerankResponseResultsItemDocument(text='Stephen Hawking was a theoretical physicist who worked on black holes and cosmology.'), index=2, relevance_score=0.015543648)] meta=ApiMeta(api_version=ApiMetaApiVersion(version='1', is_deprecated=None, is_experimental=None), billed_units=ApiMetaBilledUnits(images=None, input_tokens=N

In [ ]:
response.results[0].document.text

'Albert Einstein was a theoretical physicist who developed the theory of relativity.'

In [ ]:
response.results[0].relevance_score

0.99931216

In [ ]:
for i in range(4):
  print(f"text: {response.results[i].document.text} score: {response.results[i].relevance_score}")

text: Albert Einstein was a theoretical physicist who developed the theory of relativity. score: 0.99931216
text: Isaac Newton formulated the laws of motion and universal gravitation. score: 0.050705366
text: Marie Curie conducted pioneering research on radioactivity and won two Nobel Prizes. score: 0.028167473
text: Stephen Hawking was a theoretical physicist who worked on black holes and cosmology. score: 0.015543648


In [ ]:
reranked_documents

[('Albert Einstein was a theoretical physicist who developed the theory of relativity.',
  np.float64(1.6785247392286016)),
 ('Marie Curie conducted pioneering research on radioactivity and won two Nobel Prizes.',
  np.float64(0.0)),
 ('Stephen Hawking was a theoretical physicist who worked on black holes and cosmology.',
  np.float64(0.0)),
 ('Isaac Newton formulated the laws of motion and universal gravitation.',
  np.float64(0.0))]

In [ ]:
reranked_document_cross_encoder

[(np.float32(10.762376),
  'Albert Einstein was a theoretical physicist who developed the theory of relativity.'),
 (np.float32(2.2295616),
  'Isaac Newton formulated the laws of motion and universal gravitation.'),
 (np.float32(-5.0766177),
  'Stephen Hawking was a theoretical physicist who worked on black holes and cosmology.'),
 (np.float32(-6.810939),
  'Marie Curie conducted pioneering research on radioactivity and won two Nobel Prizes.')]